version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.1
  gcp-gke: circleci/gcp-gke@1.4.0
  kubernetes: circleci/kubernetes@1.3.1
  gcp-cli: circleci/gcp-cli@3.0.1
  slack: circleci/slack@4.12.0
  cypress: cypress-io/cypress@3

jobs:
  test:
    docker:
      - image: cypress/browsers:node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1
    resource_class: small
    working_directory: ~/repo

    steps:
      - checkout
      - run: apt-get update && apt-get install -y curl
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - ~/.npm
          key: v2-dependencies-{{ checksum "package.json" }}

      - cypress/run-tests:
          cypress-command: 'npm run cy:run'
      - store_artifacts:
          path: cypress/screenshots
      - slack/notify:
          channel: deployments
          event: fail
          template: basic_fail_1

  k8s:
    docker:
      - image: docker.io/danielspeixoto/gke-cli
    resource_class: small
    description: Deploy application to Google Kubernetes Engine
    steps:
      - checkout
      - gcp-cli/setup:
          version: 462.0.0
      - kubernetes/install
      - run:
          name: Authenticate with cluster
          command: gcloud container clusters get-credentials "$CLUSTER_NAME" --region="$GOOGLE_COMPUTE_REGION"
      - run:
          name: Defines image tag
          command: sed -i "s/{{IMAGE_TAG}}/$CIRCLE_SHA1/g" kubernetes/deployment.yaml
      - kubernetes/create-or-update-resource:
          resource-file-path: kubernetes/cronjob.yaml
      - slack/notify:
          channel: deployments
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: deployments
          event: pass
          template: basic_success_1

workflows:
  deploy:
    when:
      equal: [main, << pipeline.git.branch >>]
    jobs:
      - test:
          context:
            - notifiers
      - gcp-gcr/build-and-push-image:
          image: oppenheimer
          tag: $CIRCLE_SHA1
          context: gke
      - k8s:
          context:
            - gke
            - notifiers
          requires:
            - gcp-gcr/build-and-push-image
