version: 2.1

orbs:
  slack: circleci/slack@4.12.0
  cypress: cypress-io/cypress@3

jobs:
  build-and-test:
    docker:
      - image: cypress/browsers:node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1
    working_directory: ~/repo

    steps:
      - checkout
      - run: apt-get update && apt-get install -y curl
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - ~/.npm
          key: v2-dependencies-{{ checksum "package.json" }}

      - cypress/run-tests:
          cypress-command: 'npm run cy:run'
      - store_artifacts:
          path: cypress/screenshots
      - slack/notify:
          channel: test
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: test
          event: pass
          template: basic_success_1

workflows:
  test:
    jobs:
      - build-and-test:
          context:
            - notifiers