apiVersion: batch/v1
kind: CronJob
metadata:
  name: oppenheimer-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: oppenheimer
            image: gcr.io/inner-autonomy-371516/oppenheimer:{{IMAGE_TAG}}
            command: ["npm", "run", "cy:run"]
          restartPolicy: Never