apiVersion: batch/v1
kind: CronJob
metadata:
  name: oppenheimer-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: oppenheimer
            image: gcr.io/inner-autonomy-371516/oppenheimer:{{IMAGE_TAG}}
            command: ["/bin/bash", "-c", "./run.sh"]
            env:
            - name: CIRCLE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: oppenheimer-secrets
                  key: circleci
                  optional: false
          restartPolicy: Never
