apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: run-tests-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: run-tests
            image: gcr.io/inner-autonomy-371516/hippocrates:{{IMAGE_TAG}}
          restartPolicy: OnFailure